### ISSUE TITLE
Optional genotype data checksum tracking

### ISSUE THREAD

**Issue by nevrome** [poseidon-framework/poseidon-schema#28]
We generally want to make sure that a certain version  of a poseidon package (as defined by the `packageVersion` field in the POSEIDON.yml) is guaranteed to contain a specific set and state of files. With our current setup this can not be guaranteed.

One way to ensure version correctness is with version control systems like Git. But this is an extrinsic solution wrapping around the package, not anchored in the package files itself. It's also no good solution for the large genotype data files.

Another possible way to solve this would be to store checksums within the POSEIDON.yml file. The most popular checksum is the [MD5-hash](https://en.wikipedia.org/wiki/MD5).

I suggest to add the following (optional) fields to the POSEIDON.yml file (here filled with random hashes):

```
checksums:
  genoFileCheck: 1a0e41e119ea76e8a1a524b3cba3dcee
  snpFileCheck: 732b526bc1d6475c785479f77e8549d0
  indFileCheck: f39eb9030d4d2891fc3781b79f5daf7a
  jannoFileCheck: dffd8f675c4bddec2639a6851ca3930d
  bibFileCheck: 4c9808dda6567044324ad185fc25ca0e
```

These fields can be optional for people who quickly want to get their data usable in the poseidon framework. For our stable data repositories we should use them, or at least `genoFileCheck` and `snpFileCheck`, as these two files are not monitored by Git.

Out tooling should be able to consider these checksums. This mostly concerns `trident validate` and `trident init` at the moment. The latter should also automatically create checksums or maybe even add them to already established POSEIDON.yml files.
