### ISSUE TITLE
Data source/preparation pipeline

### ISSUE THREAD

**Issue by nevrome** [poseidon-framework/poseidon-schema#32]
As discussed today we have to find a solution to preserve genotype data quality and document the preparation pipeline for each package. I opened this issue to discuss the concrete implementation.

Probably we should have an optional field in the POSEIDON.yml for that. Something like `genotypeDataPreparationProtocol`. We could limit this field to a hard selection of protocols (like `AARD` or `MPI-SHH-DAG`), where each of these values references a specific computational data preparation workflow starting with FASTQ or BAM-files. 

For `AARD` we only know what's written on the [website](https://reich.hms.harvard.edu/allen-ancient-dna-resource-aadr-downloadable-genotypes-present-day-and-ancient-dna-data): 
> The genotypes in the AADR are not always a perfect match to those from the associated published papers. This is because to make it easier to coanalyse datasets we have started from bam or fastq files, trimmed the ends of sequences to reduce errors due to ancient DNA damage in a way that is largely uniform across datasets, which may be slightly different from that used in the individual publications, and determined genotypes anew by sampling a random sequence to cover each position. 

For `MPI-SHH-DAG` (or a different name for "our" procedure) we should imho prepare a good documentation of the workflow - maybe with protocols.io (or or any other publication medium). The latter would indeed support computational workflows (e.g. [here](https://www.protocols.io/view/de-novo-transcriptome-assembly-workflow-ghebt3e)). Ideally we would have such a documentation also for the AARD, but that's not on us.

An additional question: What about modern data? It probably goes neither through the `AARD` nor the `MPI-SHH-DAG` pipeline.

Independent of this we could also store data source information in the POSEIDON.yml. This could even replace the individual-wise information we planned in #30. I imagine an optional list field `rawSequencingDataSource`, maybe like this:

```
rawSequencingDataSource:
- archive: ENA
  accession: BN000065
  url: https://www.ebi.ac.uk/ena/browser/view/BN000065
- archive: SRA
  accession: SRR000001
  url: https://trace.ncbi.nlm.nih.gov/Traces/sra/sra.cgi?view=run_browser&run=SRR000001
- url: https://www.my_website.org/my_sequencing_data/1234
- archive: zenodo
  doi: 10.5281/zenodo.3346055
```
Each list entry has one or multiple of `archive`, `accession`, `url` or `doi`.
